<%@ Page Title="Home Page" Async="true" Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="JTF_Memory_AspNet._Default" %>
<html>
    <head>
        <title>Memory Leak Demo</title>
    </head>
    <body>
        <script
          src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
        <script src="Scripts/jquery.signalR-2.4.0.min.js"></script>
        <!--Reference the autogenerated SignalR hub script. -->
        <script src="signalr/hubs"></script>
        <script type="text/javascript">
            $(function () {
                var ctx = document.getElementById('myChart');
                var lineChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        datasets: [{
                            label: 'Memory Used (MB)'
                        }]
                    },
                    options: {
                        scales: {
                            xAxes: [{
                                type: 'time',
                                time: {
                                    unit: 'second'
                                },
                                scaleLabel: {
                                    display: true,
                                    labelString: 'Time'
                                }
                            }],
                            yAxes: [{
                                display: true,
                                scaleLabel: {
                                    labelString: 'Memory Used (MB)'
                                },
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }

                });

                // Declare a proxy to reference the hub. 
                var hub = $.connection.memoryHub;
                // Create a function that the hub can call to broadcast messages.
                hub.client.displayData = function (text) {
                    $('#data').text(text);                   
                };

                hub.client.displayMemory = function (data) {
                    lineChart.data.datasets.forEach((dataset) => {
                        dataset.data.push({
                            x: new Date(),
                            y: data
                        });
                    });
                    lineChart.update();
                }
               
                // Start the connection.
                $.connection.hub.start().done(function () {
                    $('#start').click(function () {                                               
                        hub.server.startProcess(true);
                    });

                    $('#start-noleak').click(function () {
                        hub.server.startProcess(false);
                    });

                    $('#gc').click(function () {
                        hub.server.triggerGC();
                    });
                });

                
            });
        </script>

        <div id="graph" style="height:350px; width:800px;">
            <canvas id="myChart" height="350" width="800"></canvas>
        </div>
        <div id="data">

        </div>

        <button id="start">Start (With Leak)</button>
        <button id="start-noleak">Start (Without Leak)</button>
        <button id="gc">Trigger GC.Collect</button>
    </body>
</html>
